# ----------------------------------------------------------------
# Fluid 主题专用配置
# ----------------------------------------------------------------

# 浏览器标签栏图标
favicon: /img/fluid.png
apple_touch_icon: /img/fluid.png

# 导航栏设置
navbar:
  blog_title: "My Blog"

  ground_glass:
    enable: true
    px: 3
    alpha: 0.3
  
  
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }

# 首页设置
index:
  banner_img: /img/1000003553.jpg
  # 去掉大图上方的蓝色遮罩，让你的红色透出来
  # banner_mask_alpha: 0
  text: "ATIT - 探索与记录"
  slogan:
    enable: true
    text: "hola"
  post_url_target: _blank
  post_meta: { date: true, category: true, tag: true }

# 文章页设置
post:
  banner_img: /img/default.png

  share:
    enable: false
  copyright:
    enable: true
    content: '本博客所有文章除特别声明外，均采用 CC BY-SA 4.0 许可协议。转载请注明出处！'
  meta:
    author: { enable: true }
    date: { enable: true, format: "YYYY-MM-DD HH:mm" }
  updated: { enable: false }
  prev_next: { enable: true }

# ----------------------------------------------------------------
# 颜色配置（重点：白天和黑夜模式都在这里统一管理）
# ----------------------------------------------------------------

color:
  # --- 白天模式 ---
  # body_bg_color: "#841021"
  body_bg_color_dark: "#841021"
  board_color_dark: "#FF7DB6"
  navbar_bg_color: "#841021"
  navbar_bg_color_next: "#841021"
  navbar_bg_color_dark: "#ffffff"
  link_color: "#2f4154"
  
      
  

# 脚注设置
footer:
  content: '<span>Fuck Made with Hexo & Fluid</span>'
